-- Generated by npm run supabase:seed:generate
-- Source: src/content/**/*.md

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('art', 'quiet-window-study', true, '{"title":"静窗习作","date":"2026-01-12T00:00:00.000Z","year":2026,"creator":"替换为创作者姓名","medium":"纸上综合媒介","category":"experiments","dimensions":"替换为作品尺寸","coverImage":"artPaperStudy","coverAlt":"由层叠纸形构成的抽象作品占位图","excerpt":"一篇关于光、纸与记忆的安静习作占位条目。","caption":"替换为关于完成作品的说明。","gallery":[{"imageKey":"artPaperStudy","alt":"主要作品习作占位图","caption":"主习作占位说明。"},{"imageKey":"artWindowLight","alt":"第二张抽象作品占位图","caption":"过程图片或相关图片占位说明。"}],"featured":true,"published":true,"tags":["占位","纸","光"],"order":1}'::jsonb, '这是一段用于作品详情页的故事占位文字。请替换为塑造这件完成作品的记忆、过程、材料和那些细小决定。

详情页会把故事视为作品的一部分，而不是把它藏在元数据下面。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('art', 'soft-geometry', true, '{"title":"柔软几何","date":"2025-11-02T00:00:00.000Z","year":2025,"creator":"替换为创作者姓名","medium":"数字习作","category":"digital art","coverImage":"artWindowLight","coverAlt":"带有窗形元素的抽象作品占位图","excerpt":"第二件示例作品，用来展示不同画幅比例如何共处于画廊中。","gallery":[{"imageKey":"artWindowLight","alt":"窗边光影数字占位图","caption":"替换为一段过程说明。"}],"featured":false,"published":true,"tags":["占位","数字"],"order":2}'::jsonb, '把这一段替换为作品的背景：它为什么被创作、它在研究什么，以及它在你们共同档案中的位置。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('lifestyle', 'a-found-essay', true, '{"title":"一篇关于注意力的文章","date":"2026-03-18T00:00:00.000Z","contentType":"external","author":"替换为策展人姓名","sourceName":"外部来源占位","externalUrl":"https://example.com","coverImage":"lifestyleShelf","coverAlt":"书架与笔记的抽象占位图","excerpt":"一张外部发现示例卡片，包含私人备注和安全的外部链接。","personalNote":"我们保存这篇文章，是为了提醒自己留意普通日子。请替换为你真正想分享它的原因。","featured":true,"published":true,"tags":["我们发现的事物","文章"],"order":2}'::jsonb, '这则条目展示如何收纳一个外部发现。可以在这里保留一段简短的私人备注，然后通过安全的外部链接把访客带到原始来源。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('lifestyle', 'morning-table-notes', true, '{"title":"晨间餐桌札记","date":"2026-02-04T00:00:00.000Z","contentType":"original","author":"替换为作者姓名","coverImage":"lifestyleTable","coverAlt":"安静餐桌场景的抽象占位图","excerpt":"一篇关于日常观察、餐食、书本与居家仪式的原创故事占位内容。","personalNote":"替换为你对这个时刻的私人备注。","featured":true,"published":true,"tags":["家","食物","日常"],"order":1}'::jsonb, '这篇原创生活故事是占位内容。你可以把它替换成一段反思、一道食谱、一次房间更新、一则读书笔记、一个小小里程碑，或任何属于生活档案的内容。

这个版式支持长文、图片，以及需要时嵌入的媒体内容。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('travel', 'garden-walk', true, '{"title":"花园散步","destination":"替换为目的地","country":"替换为国家或地区","startDate":"2025-09-10T00:00:00.000Z","year":2025,"coverImage":"travelGarden","coverAlt":"花园小径的抽象占位图","excerpt":"第二篇旅行条目，用来展示桌面端时间线的交错排布。","tripCategory":"午后札记","gallery":[{"imageKey":"travelGarden","alt":"花园小径占位图","caption":"替换为真实旅行图片。"}],"highlights":["替换为一个你想记住的细节。"],"featured":false,"published":true,"tags":["占位","花园"],"order":2}'::jsonb, '把这段故事替换为旅途中真实的记忆、照片和图片说明。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('travel', 'winter-coastline', true, '{"title":"冬日海岸线","destination":"替换为目的地","country":"替换为国家或地区","startDate":"2026-01-20T00:00:00.000Z","endDate":"2026-01-24T00:00:00.000Z","year":2026,"coordinates":{"lat":0,"lng":0},"coverImage":"travelCoast","coverAlt":"柔和海岸线的抽象占位图","excerpt":"一篇用于时间线展示的旅行示例，未包含真实的私人位置细节。","tripCategory":"安静旅程","gallery":[{"imageKey":"travelCoast","alt":"海岸线占位图","caption":"替换为真实照片和说明。"},{"imageKey":"travelGarden","alt":"花园小径旅行占位图","caption":"可选的第二张旅行图片占位说明。"}],"highlights":["替换为一个值得记住的瞬间。","替换为一顿喜欢的饭、一次散步或一处风景。"],"featured":true,"published":true,"tags":["占位","海岸"],"order":1}'::jsonb, '这篇旅行故事是完整旅程页面的占位内容。请替换为真实记忆、横向大图、图片网格、说明文字、可选行程笔记和记忆亮点。

公开条目中请避免加入实时精确位置或私人旅行计划。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;
