-- Generated by npm run supabase:seed:generate
-- Source: src/content/**/*.md

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('art', 'collected-glimmers', true, '{"title":"微光集","date":"2026-05-08T00:00:00.000Z","year":2026,"creator":"Wisteria Archive","medium":"纸上光影与数字拼贴","category":"illustration","dimensions":"两页小型样册","coverImage":"artRetroStudio","coverAlt":"复古工作室中的画架、纸张和暖色灯光","excerpt":"收集工作室里短暂光影的两页示例册。","caption":"沉浸式书册版式夹具。","gallery":[],"featured":true,"published":true,"tags":["沉浸式夹具","光"],"order":3,"book":{"artifactId":"collected-glimmers","kind":"book","fixture":true,"noindex":true,"cover":{"titleZh":"微光集","titleEn":"COLLECTED GLIMMERS","emblem":"sun","color":"#6b3940","foil":"#d9b66c"},"pages":[{"layout":"prose-image","imageKey":"artRetroStudio","imageAlt":"暖色灯光下摆放画架与纸张的复古工作室","imageCaption":"示例图版 · 光停在纸面上的几分钟"},{"layout":"prose"}]}}'::jsonb, '# 微光集

有些作品从完整的构图开始，有些只从桌角的一块亮色开始。这册样本收集后者：玻璃上的反光、纸张翘起的边缘，以及颜料尚未干透时的微小光泽。

<!-- page -->

## 第二页：保留未完成

记录并不要求事物已经完成。日期、材料和一张过程图片足以让某个瞬间在未来重新变得清晰。

*This sample volume can later become a sketchbook, portfolio note, or miniature exhibition catalogue.*')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('lifestyle', 'wisteria-field-notes', true, '{"title":"紫藤镇手记","date":"2026-08-20T00:00:00.000Z","contentType":"original","author":"Wisteria Archive","coverImage":"lifestyleRetroMorning","coverAlt":"暖色晨光中的桌面与手记","excerpt":"放在图书馆阅览桌上的四页观察手记示例。","personalNote":"这是一册可替换的沉浸式阅读夹具。","featured":true,"published":true,"tags":["沉浸式夹具","手记"],"order":1,"book":{"artifactId":"wisteria-field-notes","kind":"book","fixture":true,"noindex":true,"cover":{"titleZh":"紫藤镇手记","titleEn":"WISTERIA FIELD NOTES","emblem":"wisteria","color":"#6f2f3c","foil":"#d3ad62"},"pages":[{"layout":"title"},{"layout":"prose-image","imageKey":"lifestyleRetroMorning","imageAlt":"晨光照在桌面、杯子和手记上","imageCaption":"清晨九点，阅览室的灯仍然亮着。"},{"layout":"prose"},{"layout":"prose"}]}}'::jsonb, '# 第一则观察

海风穿过高窗时，书页会先于窗帘轻轻移动。我们把这个微小的先后顺序记下来，像记住一条只有清晨才出现的路。

*Field note 01 · The pages notice the sea breeze first.*

<!-- page -->

## 阅览桌

黄铜灯把桌面照成一座小岛。杯沿、铅笔和旧纸张各自留下短短的影子；它们不急着说明什么，只邀请人多停留一会儿。

<!-- page -->

## 今日收藏

- 一枚从书脊间落下的干花瓣
- 门廊外三次远远的钟声
- 地毯上被晨光照亮的一小段红色

这些内容只是版式夹具，之后可以替换为真实札记、照片或共同记忆。

<!-- page -->

## 离开之前

合上手记时，不必为这一天写下结论。留下日期、天气，以及仍然想再看一次的事物，就已经足够。

*End of sample volume · Replace with your own field notes.*')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;

insert into public.content_entries (collection, slug, published, data, body_markdown)
values ('travel', 'atlas-of-tides', true, '{"title":"潮汐图谱","destination":"Wisteria Coast","country":"Imagined Archive","startDate":"2026-06-12T00:00:00.000Z","endDate":"2026-06-15T00:00:00.000Z","year":2026,"coverImage":"travelRetroCoast","coverAlt":"复古海岸列车与蓝色海湾","excerpt":"一册由海岸线、航标与潮汐札记组成的四页示例图谱。","tripCategory":"航海图谱","gallery":[],"highlights":["潮线与旧码头的方向标记","傍晚返航时的金色水面"],"featured":true,"published":true,"tags":["沉浸式夹具","海岸"],"order":2,"book":{"artifactId":"atlas-of-tides","kind":"book","fixture":true,"noindex":true,"cover":{"titleZh":"潮汐图谱","titleEn":"ATLAS OF TIDES","emblem":"wave","color":"#244f58","foil":"#d1ad62"},"pages":[{"layout":"title"},{"layout":"image","imageKey":"travelRetroCoast","imageAlt":"沿着海湾行驶的复古列车与远处帆船","imageCaption":"示例图版 · 北岸慢车与午后潮线"},{"layout":"prose"},{"layout":"prose"}]}}'::jsonb, '# 潮汐图谱

这不是一张用于抵达的地图，而是一份关于等待的记录：潮水何时盖住礁石，帆影何时越过钟楼，以及哪一种蓝色只在黄昏出现。

*Atlas plate I · A map for noticing, not arriving.*

<!-- page -->

## 北岸图版

图中的海岸、列车与帆船是可替换的示例图片。未来每一页都可以收纳真实旅程中的横幅照片、手绘路线或旧票据。

<!-- page -->

## 航标记录

从图书馆高窗望去，海岸向南弯曲。三座塔、一道桥和港口外的白帆构成了返航时最容易辨认的顺序。

当雾落下来，先寻找灯，再寻找水面的倒影。

<!-- page -->

## 潮水退去以后

沙滩会暂时保留绳索、贝壳和脚步的轮廓。图谱的最后一页留白，是为了让下一次散步决定它应当收藏什么。')
on conflict (collection, slug) do update set
  published = excluded.published,
  data = excluded.data,
  body_markdown = excluded.body_markdown,
  body_html = null;
